import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Home from "./header";
import "./globals.css";
import Themeprovider from "./_provider/themeprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Themeprovider>
      <Home />
      {children}
    </Themeprovider>
  );
}
